name: 'Update with Upstream'
description: 'Update repo with upstream'
author: 'Mark E. Anderson'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  repo:
    description: 'Repository Name'
    required: true
  op-token:
    description: '1Password Service Account Token'
    required: true

runs:
  using: node20
  main: dist/index.js
